### ISSUE TITLE
Just dropping by to say thanks.

### ISSUE THREAD

**Issue by drossbox** [grumlimited/authenticator-rs#102]
I've had a few problems with authenticator over the last year, and stumbled across your project through the AUR - massive thanks for building this. Does everything I need and works great, so wanted you to know your work on it is really appreciated!

**Comment by gr211** [comment]
Thanks. Appreciations very much appreciated :-)
Please let me know if you find any issues and/or improvements might be needed in places. Still needing to grow user base to build some sort of momentum.
