### ISSUE TITLE
ARM binaries?

### ISSUE THREAD

**Issue by MatejLach** [grumlimited/authenticator-rs#116]
Thanks for working on `authenticator-rs`, hands down the best TOTP 2FA app for Linux. 

It would be really cool if you could cross compile `aarch64` binaries in addition to x64 so that devices like the PinePhone, where [a build of Arch Linux ARM](https://github.com/dreemurrs-embedded/Pine64-Arch) is particularly popular and having `authenticator-rs` available there would be a major use case.

Thanks.

**Comment by gr211** [comment]
Hey hi @MatejLach 
I'm afraid I've never compiled for arm before, and would not even know how to "test" the build.
Ill do some research, but if you happen to know the steps to cross-compile, that might save me quite a bit of time

**Comment by gr211** [comment]
Hey  @MatejLach 
I did try cross compiling but it's more involved than I've the time to invest in for a platform I unfortunately do not use.
