### ISSUE TITLE
touch-friendly UI

### ISSUE THREAD

**Issue by 3nprob** [grumlimited/authenticator-rs#121]
authenticator-rs is a great candidate for small touch devices.

One thing that could help a lot would be to make the tap/click on any part of the  row (sans the context menu button) into copying the code.

Increased column height could also be nice.

**Comment by gr211** [comment]
I would need to do some research on how to on this one. It's been designed as a desktop application. Would need to find out how practical it'd be for the UI to become adaptive in that way.

**Comment by 3nprob** [comment]
> I would need to do some research on how to on this one. It's been designed as a desktop application. Would need to find out how practical it'd be for the UI to become adaptive in that way.

Tried it on the Pinephone and it's not too far off already, I may upload some screenshots in the issue.

**Comment by gr211** [comment]
No screenshots :-( closing
