### ISSUE TITLE
Allow user configuration

### ISSUE THREAD

**Issue by 3nprob** [grumlimited/authenticator-rs#122]
Ideally configurable with UI, but a toml,  ini, or yaml  in `~/.config/authenticator-rs` should be sufficient.

Suggested entries:

- [ ] Data directory location
- [ ] Column height (S/M/L) (see #121)

**Comment by gr211** [comment]
Suppose it could use GSettings for this ?

**Comment by 3nprob** [comment]
Technically yes, though I guess it depends on your perspective.

From my perspective as a user in a GNOME environment these are the reasons why this doesn't solve it for me personally:
* I value being able to edit my configuration as text files
* I value being able to manage and share my configuration in source control using tools like git and dotfiles management like chezmoi

IMO gsettings are great for their original use-case: Configuring local gnome/gtk services.

There's also already gnome-authenticator which is fully integrated with gtk/gnome/gsettings, so from that perspective it could be nice to provide an alternative?

Just my 5c, it would be interesting to hear your thoughts on this and if you have an intended direction.

**Comment by gr211** [comment]
Authenticator-rs was always intended to being fully integrated with gtk/gnome/gsettings actually. I wanted it to be as close as I can make it to be to the original python (now rust) authenticator. Offering an alternative could have merit. If and when some significant amount of users deem it a better approach, I could move away from gsettings. Don't get me wrong, I value the time and effort you put into presenting your arguments. Yet with the time I have, and considering not using gsettings is not something I need, I cant really afford to change that now.

**Comment by 3nprob** [comment]
Thanks for taking the time to explain :)
