### ISSUE TITLE
Allow storing secrets in database instead of keyring

### ISSUE THREAD

**Issue by 3nprob** [grumlimited/authenticator-rs#123]
Motivations:
- Facilitate automated backup and sync
- Allow running in environments without keyring
- Interoperbility

I guess this would depend on #122 .

Ideally secrets would be encrypted with a passphrase prompted for on application start and dropped after decryption.

**Comment by 3nprob** [comment]
Slightly different but could solve the same motivations: https://himitsustore.org/

**Comment by 3nprob** [comment]
@gr211 What would your stance be on migrating to using [sqlcipher](https://github.com/sqlcipher/sqlcipher)? Something you'd be open to a PR for? That would allow encrypting the entire database. It should be fully supported by rusqlite for some time now so aside for adding a flow for asking the user for a passphrase it shouldn't be a big effort to do i think.

**Comment by gr211** [comment]
I dont know tbh. I went to some length to integrate with secret-service. It used to be some plain sqllite db in earlier iterations. I would need quite a change of heart on this one. And time ;-)

**Comment by 3nprob** [comment]
Not saying I'm going to jump right at it now, but if someone comes along and implements support for using either. For example the default of using secret-service like today could be overridden if #122 is implemented.

Or is that also something you're still on the fence on?

(Arguably this would be better addressed by having alternative providers for secret-service that would utilize the intended storage backend - so using files/db directly is a bit of a capitulation to the fact that that ain't happening anytime soon)

**Comment by 3nprob** [comment]
Closing per [#122 ](https://github.com/grumlimited/authenticator-rs/issues/122#issuecomment-1173921024)
