### ISSUE TITLE
Make way for importing Google authenticator exports

### ISSUE THREAD

**Issue by imahbub** [grumlimited/authenticator-rs#135]
Hi, is there any current or planned way to import Google authenticator exports?

**Comment by jacobgkau** [comment]
I ran into this today-- I tried to import a photo of a QR code from Google Authenticator, but I found the QR code's text wasn't in the proper format for Authenticator RS to import.

As a workaround, you can scan the QR code using [extract_otp_secrets](https://github.com/scito/extract_otp_secrets), then copy/paste the secret into authenticator-rs.

(There are other apps that can provide the secret from Google Authenticator QR code, like [google_authenticator_exporter](https://github.com/krissrex/google-authenticator-exporter), but extract_otp_secrets provides prebuilt binaries for convenience, supports scanning the QR code directly, and even supports Google Authenticator's multi-account QR codes so you don't have to export each one individually.)

**Comment by gr211** [comment]
@imahbub 
@jacobgkau 

Thanks for reporting this issue.
Released version 0.8.0 which can import Google authenticator exports (as a QRCode image).
I do not use this application though. Not sure if other export types are available from GA.
