### ISSUE TITLE
Account is edited instead of added after an edit is cancelled or completed

### ISSUE THREAD

**Issue by jacobgkau** [grumlimited/authenticator-rs#65]
**Steps to reproduce:**
- Click the three dots next to an account -> Edit
- Click Cancel
- Click the + icon -> Add account
- Attempt to add an account

**Expected behavior:** The added account should be added to the accounts list.

**Actual behavior:** The added account replaces the account I last clicked "Edit" on.

(Thank you so much for making this app!)

**Comment by gr211** [comment]
Thanks a lot for the feedback @jacobgkau .
Fixing it in https://github.com/grumlimited/authenticator-rs/pull/67

**Comment by jacobgkau** [comment]
Confirmed the fix works, so closing this issue.
